let state, screen = 'dashboard', selectedId = 'REQ-GAME-2048', notice = '';
const app = document.querySelector('#app');
const icon = `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.6c2.9 0 5.3 2.3 5.3 5.2v4.1a5.3 5.3 0 0 1-10.6 0V7.8C6.7 4.9 9.1 2.6 12 2.6Zm-3.6 5a3.6 3.6 0 0 1 7.2 0v4.4a3.6 3.6 0 0 1-7.2 0V7.6Zm2.8 9.3h1.6v2.1h-1.6v-2.1Zm-4.5-1.5h10.6v1.7H6.7v-1.7Z"/></svg>`;
const fmt = d => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(d));
const badge = s => `<span class="badge ${s.toLowerCase().replaceAll(' ', '-')}"><i></i>${s}</span>`;
const req = id => state.requests.find(r => r.id === id);
const authFor = id => state.authorizations.find(a => a.request_id === id);
async function api(url, options) { const r = await fetch(url, options); if (!r.ok) throw new Error((await r.json()).error); return r.json(); }
async function load() { state = await api('/api/state'); render(); }
function nav() { return `<aside><div class="brand"><div class="brandmark">${icon}</div><span>Voice<span>Passport</span></span></div><div class="nav"><button class="${screen === 'dashboard' ? 'active' : ''}" onclick="go('dashboard')">⌂ <b>Dashboard</b></button><button class="${screen === 'requests' ? 'active' : ''}" onclick="go('requests')">▣ <b>Requests</b><em>${state.requests.filter(x => x.status === 'PENDING').length}</em></button><button class="${screen === 'permissions' ? 'active' : ''}" onclick="go('permissions')">◇ <b>Permissions</b></button></div><div class="passport-mini"><small>VOICE PASSPORT</small><strong>${state.voice.name}</strong><span>${badge(state.voice.status)}</span><p>${state.voice.id} · ${state.voice.creator}</p></div><button class="reset" onclick="resetDemo()">↻ Reset demo</button></aside>` }
function header(title, kicker = 'VOICE PASSPORT') { return `<header><div><small>${kicker}</small><h1>${title}</h1></div><div class="privacy">◉ Minimal disclosure<br/><span>Only decision-required information is shared.</span></div></header>` }
function dashboard() { let active = state.authorizations.filter(a => a.status === 'ACTIVE').length, pending = state.requests.filter(r => r.status === 'PENDING').length; return `${header('Creator control, made portable.')}<section class="hero"><div><span class="eyebrow">${badge(state.voice.status)} &nbsp; ${state.voice.id}</span><h2>${state.voice.name}</h2><p>Owned by <b>${state.voice.creator}</b> · A portable consent layer for AI-generated voices.</p></div><button class="primary" onclick="go('requests')">Review Requests <span>→</span></button></section><div class="stats"><div><small>ACTIVE AUTHORIZATIONS</small><strong>${active}</strong></div><div><small>PENDING REQUESTS</small><strong>${pending}</strong></div><div><small>AUDIT RECEIPTS</small><strong>${state.receipts.length}</strong></div></div><section class="section-head"><div><small>CONSENT POLICY</small><h2>What this voice passport permits</h2></div><button class="link" onclick="go('permissions')">View all permissions →</button></section><div class="policy-grid">${state.permissions.map(p => `<article class="policy"><div class="policy-icon ${p.tone}">${p.tone === 'positive' ? '✓' : p.tone === 'negative' ? '×' : '!'}</div><div><h3>${p.label}</h3>${badge(p.status)}</div></article>`).join('')}</div><section class="claim"><div class="claimicon">✦</div><div><small>THE PASSPORT CLAIM</small><h2>“This creator has authorized this application to use this voice for a specific purpose, within a defined scope and time period, under explicit restrictions.”</h2></div></section>` }
function requests() { return `${header('Permission requests', 'REQUEST INBOX')}<div class="request-layout"><div class="request-list">${state.requests.map(r => `<button class="request-row ${selectedId === r.id ? 'chosen' : ''}" onclick="selectRequest('${r.id}')"><div class="avatar">${r.requester.slice(0, 2).toUpperCase()}</div><div><strong>${r.requester}</strong><p>${r.purpose}</p><small>${fmt(r.created_at)}</small></div>${badge(r.status)}</button>`).join('')}</div><div>${requestDetail(req(selectedId))}</div></div>` }
function requestDetail(r) { if (!r) return '<div class="card">Select a request.</div>'; let auth = authFor(r.id); return `<article class="card request-card"><div class="card-top"><div><small>PERMISSION REQUEST</small><h2>${r.requester}</h2><p>Request to use <b>${state.voice.name}</b></p></div>${badge(r.status)}</div><div class="explanation">${r.requester} is requesting permission to generate synthetic speech using this voice for <b>${r.purpose.toLowerCase()}</b> for <b>${r.duration} days</b>.</div><dl><div><dt>VOICE</dt><dd>${state.voice.name}<span>${state.voice.id}</span></dd></div><div><dt>PURPOSE</dt><dd>${r.purpose}</dd></div><div><dt>REQUESTED ACTION</dt><dd>${r.requested_action}</dd></div><div><dt>DURATION</dt><dd>${r.duration} days</dd></div><div><dt>MODEL TRAINING</dt><dd>${r.model_training ? 'Requested' : 'Not permitted'}</dd></div><div><dt>RESALE</dt><dd>${r.resale ? 'Requested' : 'Not permitted'}</dd></div></dl>${r.status === 'PENDING' ? `<button class="primary wide" onclick="go('review')">Review Request <span>→</span></button>` : auth ? `<button class="primary wide" onclick="go('authorization')">View Authorization <span>→</span></button>` : `<button class="secondary wide" onclick="go('receipt')">View Decision Receipt <span>→</span></button>`}</article>` }
function policyFor(r) { const purpose = r.purpose.toLowerCase(); if (purpose === 'game character dialogue') return { allowed: true, label: 'POLICY ALLOWS', items: ['✓ Game dialogue permitted', '✓ Synthetic voice generation within scope', '✓ Model training prohibited', '✓ Resale prohibited', 'Creator decision required'] }; if (purpose === 'commercial advertising') return { allowed: false, label: 'APPROVAL REQUIRED', items: ['⚠ Commercial advertising requires explicit approval', '✓ Model training prohibited', '✓ Resale prohibited', 'Creator decision required'] }; return { allowed: false, label: 'POLICY DENIES', items: ['⚠ This purpose is not currently authorized', '✓ Model training prohibited', '✓ Resale prohibited', 'Creator decision required'] } }
function review() { let r = req(selectedId), policy = policyFor(r); return `${header('Permission Request', 'PASSPORT REVIEW')}<article class="review"><div class="review-heading"><div class="passport-stamp">${icon}</div><div><small>REQUEST FOR ${state.voice.id}</small><h2>${r.requester} wants scoped access</h2></div>${badge(policy.label)}</div><div class="scope"><div><small>REQUESTER</small><strong>${r.requester}</strong></div><div><small>VOICE</small><strong>${state.voice.name}</strong></div><div><small>PURPOSE</small><strong>${r.purpose}</strong></div><div><small>ACTION</small><strong>${r.requested_action}</strong></div><div><small>VALIDITY</small><strong>${r.duration} days</strong></div><div><small>CREATOR CONTROL</small><strong>You control this authorization</strong></div></div><section class="policy-check"><small>PASSPORT POLICY CHECK</small>${policy.items.map(item => `<div class="${item.startsWith('⚠') ? 'caution' : ''}">${item}</div>`).join('')}</section><div class="restrictions"><span>Restrictions travel with the permission</span><div>${badge('MODEL TRAINING DENIED')} ${badge('RESALE DENIED')}</div></div><p class="disclosure">◉ Only the information required for this permission decision is disclosed. No private creator data is shared.</p><div class="decision-actions">${policy.allowed ? `<button class="primary" onclick="decide('approve')">Approve Request <span>→</span></button>` : ''}<button class="danger" onclick="decide('deny')">Deny Request</button></div></article>` }
function authorization() { let a = authFor(selectedId), r = req(selectedId), receipt = state.receipts.find(x => x.request_id === r.id); return `${header('Authorization Active', 'SCOPED AUTHORIZATION')}<article class="authorization"><div class="auth-top"><div><div class="auth-shield">✓</div><small>VOICE PASSPORT AUTHORIZATION</small><h2>${a.status === 'ACTIVE' ? 'Authorization Active' : 'Authorization ' + a.status}</h2><p>${a.status === 'REVOKED' ? 'Authorization revoked by creator. This receipt remains preserved as audit evidence.' : 'This permission is valid only for the scope below.'}</p></div>${badge(a.status)}</div><div class="scope"><div><small>REQUESTER</small><strong>${a.requester}</strong></div><div><small>VOICE</small><strong>${state.voice.name}</strong></div><div><small>PURPOSE</small><strong>${a.purpose}</strong></div><div><small>ALLOWED ACTION</small><strong>${a.scope}</strong></div><div><small>VALID UNTIL</small><strong>${fmt(a.expires_at)}</strong></div><div><small>RESTRICTIONS</small><strong>No training · No resale</strong></div></div><div class="audit-ids"><span><small>PASSPORT ID</small>${state.voice.id}</span><span><small>AUTHORIZATION ID</small>${a.id}</span><span><small>RECEIPT ID</small>${receipt.id}</span></div><div class="auth-footer"><button class="secondary" onclick="go('receipt')">View receipt →</button>${a.status === 'ACTIVE' ? `<button class="danger" onclick="confirmRevoke()">Revoke Authorization</button>` : ''}</div></article>` }
function receipt() { let r = req(selectedId), receipt = state.receipts.find(x => x.request_id === r.id), a = authFor(r.id); return `${header('Passport Receipt', 'AUDIT RECORD')}<article class="receipt"><div class="receipt-top"><div class="brand compact"><div class="brandmark">${icon}</div><span>Voice<span>Passport</span></span></div>${badge(receipt.decision)}</div><div class="receipt-title"><small>PASSPORT RECEIPT</small><h2>${receipt.id}</h2><p>An auditable record of the creator’s permission decision.</p></div><div class="receipt-grid"><div><small>PASSPORT ID</small><strong>${state.voice.id}</strong></div><div><small>RECEIPT ID</small><strong>${receipt.id}</strong></div>${a ? `<div><small>AUTHORIZATION ID</small><strong>${a.id}</strong></div>` : ''}<div><small>REQUESTER</small><strong>${r.requester}</strong></div><div><small>VOICE</small><strong>${state.voice.name}</strong></div><div><small>PURPOSE</small><strong>${r.purpose}</strong></div><div><small>DECISION</small><strong>${receipt.decision}</strong></div><div><small>TIMESTAMP</small><strong>${fmt(receipt.timestamp)}</strong></div><div><small>${a ? 'VALID UNTIL' : 'REASON'}</small><strong>${a ? fmt(a.expires_at) : receipt.reason}</strong></div></div><div class="receipt-note"><b>Restrictions:</b> Model training DENIED · Resale DENIED<br/>${a ? `Authorization: ${badge(a.status)}${a.status === 'REVOKED' ? ' · Revoked by creator.' : ''}` : `Reason: ${receipt.reason}`}</div></article>` }
function permissions() { return `${header('Voice policy', 'CONSENT POLICY')}<div class="permission-page"><h2>${state.voice.name}</h2><p>This policy travels with the voice across AI tools.</p>${state.permissions.map(p => `<div class="perm-line"><span>${p.label}</span>${badge(p.status)}</div>`).join('')}</div>` }
function render() { let page = { dashboard, requests, review, authorization, receipt, permissions }[screen](); app.innerHTML = `${nav()}<main>${notice ? `<div class="toast">${notice}</div>` : ''}${page}</main>` }
function go(s) { screen = s; notice = ''; render() } function selectRequest(id) { selectedId = id; screen = 'requests'; render() }
async function decide(action) { try { let out = await api(`/api/requests/${selectedId}/${action}`, { method: 'POST' }); state = await api('/api/state'); screen = action === 'approve' ? 'authorization' : 'receipt'; notice = action === 'approve' ? 'Scoped authorization created and receipt recorded.' : 'Request denied. A receipt has been preserved.'; render() } catch (e) { notice = e.message; render() } }
function confirmRevoke() { if (confirm('Revoke this authorization? The receipt will remain as historical evidence.')) revoke() }
async function revoke() { try { let a = authFor(selectedId); await api(`/api/authorizations/${a.id}/revoke`, { method: 'POST' }); state = await api('/api/state'); notice = 'Authorization revoked by creator. Receipt preserved.'; render() } catch (e) { notice = e.message; render() } }
async function resetDemo() { await api('/api/reset', { method: 'POST' }); screen = 'dashboard'; selectedId = 'REQ-GAME-2048'; notice = 'Demo reset.'; await load() }
load().catch(e => app.innerHTML = `<div class="error">Unable to load Voice Passport: ${e.message}</div>`);
